name: equatable
description: An abstract class that helps to implement equality without needing to explicitly override == and hashCode.
version: 0.3.0
author: Felix Angelov <felangelov@gmail.com>
homepage: https://github.com/felangel/equatable

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  collection: ^1.14.11
  meta: ^1.1.6

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  test_coverage: ^0.2.0
