name: equatable
description: A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
version: 2.0.8
repository: https://github.com/felangel/equatable
issue_tracker: https://github.com/felangel/equatable/issues
homepage: https://github.com/felangel/equatable
documentation: https://github.com/felangel/equatable
topics: [equality, equals]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.0

screenshots:
  - description: The equatable package logo.
    path: doc/assets/equatable_logo.png
